version: '3'
services:
  cron-server:
    container_name: cron-server
    image: docker.genee.in/genee/cron-server:v1.2.0-d2018032801
    network_mode: "bridge"
    volumes:
      - "./config:/usr/src/app/config"
      - "./logs:/usr/src/app/logs"
    restart: always
